### ISSUE TITLE
Conflict: multiple HTTP clients have been found in the classpath

### ISSUE THREAD

**Issue by lordofthejars** [quarkiverse/quarkus-langchain4j#2016]
When using LangChain4j 1.4.2 with:

```
<dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.langchain4j</groupId>
            <artifactId>quarkus-langchain4j-chroma</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.langchain4j</groupId>
            <artifactId>quarkus-langchain4j-ollama</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.docling</groupId>
            <artifactId>quarkus-docling</artifactId>
            <version>1.1.0</version>
        </dependency>
```

I got the following exception when trying to use ChromaDB:

```
Caused by: jakarta.enterprise.inject.CreationException: Error creating synthetic bean [3mb4Bltc2ReuR0hgutcOpGCFwaU]: java.lang.IllegalStateException: Conflict: multiple HTTP clients have been found in the classpath: [dev.langchain4j.http.client.jdk.JdkHttpClientBuilderFactory, io.quarkiverse.langchain4j.jaxrsclient.JaxRsHttpClientBuilderFactory]. Please explicitly specify the one you wish to use.
	at dev.langchain4j.store.embedding.chroma.ChromaEmbeddingStore_3mb4Bltc2ReuR0hgutcOpGCFwaU_Synthetic_Bean.doCreate(Unknown Source)
	at dev.langchain4j.store.embedding.chroma.ChromaEmbeddingStore_3mb4Bltc2ReuR0hgutcOpGCFwaU_Synthetic_Bean.create(Unknown Source)
	at dev.langchain4j.store.embedding.chroma.ChromaEmbeddingStore_3mb4Bltc2ReuR0hgutcOpGCFwaU_Synthetic_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c5(Unknown Source)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:23)
	at dev.langchain4j.store.embedding.chroma.ChromaEmbeddingStore_3mb4Bltc2ReuR0hgutcOpGCFwaU_Synthetic_ClientProxy.arc$delegate(Unknown Source)
	at dev.langchain4j.store.embedding.chroma.ChromaEmbeddingStore_3mb4Bltc2ReuR0hgutcOpGCFwaU_Synthetic_ClientProxy.addAll(Unknown Source)
	at dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(EmbeddingStoreIngestor.java:202)
	at dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(EmbeddingStoreIngestor.java:156)
	at org.acme.rag.Ingestor.ingest(Ingestor.java:49)
	at org.acme.GreetingResource.ingest(GreetingResource.java:19)
	at org.acme.GreetingResource_ClientProxy.ingest(Unknown Source)
	at org.acme.GreetingResource_Observer_Synthetic_Hc7uLOd5JUduQ_ZYiEO3m1dSiCE.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:365)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:347)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:81)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:164)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:115)
	at io.quarkus.runner.recorded.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.runner.recorded.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	... 11 more
```

Don't know if it is a bug or not, but it would be great to provide also hints on how to choose one or the other.

**Comment by geoand** [comment]
Thanks for the info!

#2032 should fix it

**Comment by bwRavencl** [comment]
Hi @geoand, 

the original issue still persists in `1.5.0.CR2` when combining `quarkus-langchain4j-chroma` with `quarkus-langchain4j-ollama`.

- `quarkus-langchain4j-chroma` depends on `langchain4j-http-client-jdk` which brings `dev.langchain4j.http.client.jdk.JdkHttpClientBuilderFactory`
- `quarkus-langchain4j-ollama` depends on `quarkus-langchain4j-jaxrs-client` which brings  `io.quarkiverse.langchain4j.jaxrsclient.JaxRsHttpClientBuilderFactory`

The stacktrace:

```
Caused by: java.lang.IllegalStateException: Conflict: multiple HTTP clients have been found in the classpath: [io.quarkiverse.langchain4j.jaxrsclient.JaxRsHttpClientBuilderFactory, dev.langchain4j.http.client.jdk.JdkHttpClientBuilderFactory]. Please explicitly specify the one you wish to use.
	at dev.langchain4j.http.client.HttpClientBuilderLoader.loadHttpClientBuilder(HttpClientBuilderLoader.java:17)
	at dev.langchain4j.store.embedding.chroma.ChromaHttpClient.<init>(ChromaHttpClient.java:37)
	at dev.langchain4j.store.embedding.chroma.ChromaClientV2.<init>(ChromaClientV2.java:22)
	at dev.langchain4j.store.embedding.chroma.ChromaClientV2$Builder.build(ChromaClientV2.java:70)
	at dev.langchain4j.store.embedding.chroma.ChromaEmbeddingStore.<init>(ChromaEmbeddingStore.java:62)
	at dev.langchain4j.store.embedding.chroma.ChromaEmbeddingStore$Builder.build(ChromaEmbeddingStore.java:176)
	at io.quarkiverse.langchain4j.chroma.runtime.ChromaRecorder$1.get(ChromaRecorder.java:29)
	at io.quarkiverse.langchain4j.chroma.runtime.ChromaRecorder$1.get(ChromaRecorder.java:19)
```

Excluding `langchain4j-http-client-jdk` from `dev.langchain4j.http.client.jdk.JdkHttpClientBuilderFactory` does not seem to be an option in this case as it seems to cause an other exception:
```
Caused by: dev.langchain4j.exception.HttpException: {"error":"ChromaError","message":"Expected request with `Content-Type: application/json`"}
	at io.quarkiverse.langchain4j.jaxrsclient.JaxRsHttpClient.execute(JaxRsHttpClient.java:121)
	at dev.langchain4j.http.client.log.LoggingHttpClient.execute(LoggingHttpClient.java:49)
	at dev.langchain4j.store.embedding.chroma.ChromaHttpClient.executeRequest(ChromaHttpClient.java:121)
```

Finally, even though the original exception states "Please explicitly specify the one you wish to use.", there seems to be no way to do exactly that.

**Comment by geoand** [comment]
Can you please https://github.com/quarkiverse/quarkus-langchain4j/pull/2048 give a try?

**Comment by myfear** [comment]
I found another one:

```
  <dependency>
            <groupId>io.quarkiverse.langchain4j</groupId>
            <artifactId>quarkus-langchain4j-ollama</artifactId>
            <version>1.2.2</version> 
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-embeddings</artifactId>
            <version>1.10.0-beta18</version>
        </dependency>
```

```
Conflict: multiple HTTP clients have been found in the classpath: [io.quarkiverse.langchain4j.jaxrsclient.JaxRsHttpClientBuilderFactory, dev.langchain4j.http.client.jdk.JdkHttpClientBuilderFactory]. Please explicitly specify the one you wish to use.
	at dev.langchain4j.http.client.HttpClientBuilderLoader.loadHttpClientBuilder(HttpClientBuilderLoader.java:17)

```

I was hoping I could just do something like this:

builder.httpClientBuilder=io.quarkiverse.langchain4j.jaxrsclient.JaxRsHttpClientBuilderFactory

But it didn't work :-(

**Comment by geoand** [comment]
Hm... We can't do much about `langchain4j-embeddings`, so you'll have to add the exclusion manually.

> builder.httpClientBuilder=io.quarkiverse.langchain4j.jaxrsclient.JaxRsHttpClientBuilderFactory

@dliubarskyi I believe we should add this, WDYT?

**Comment by geoand** [comment]
Okay, I'll add that tomorrow

**Comment by geoand** [comment]
https://github.com/langchain4j/langchain4j/pull/4397
